name: test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Runs a single command using the runners shell
      - name: run docker build
        id: migration
        run: |
          git diff --name-only @^ -- db/migrate
          SIZE=$(git diff --name-only @^ -- db/migrate | wc -l)
          echo "::set-output name=size::$SIZE"
          echo ${{ github.ref }}

  migration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: check migration
        id: migration
        run: |
          git diff --name-only @^ -- db/migrate
          SIZE=$(git diff --name-only @^ -- db/migrate | wc -l)
          echo "::set-output name=size::$SIZE"
          
      - name: run migration
        if: steps.migration.outputs.size != '0'
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
