name: test2

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: run docker build
        run: |
          echo run docker build

  migration:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: configure deploy env
        if: github.ref == 'refs/heads/main'
        run: echo "deploy_env=production" >> $GITHUB_ENV

      - name: check migration
        id: migration
        run: |
          git diff --name-only @^ -- db/migrate
          SIZE=$(git diff --name-only @^ -- db/migrate | wc -l)
          echo "::set-output name=size::$SIZE"

      - name: run migration
        if: steps.migration.outputs.size != '0' && ( env.deploy_env == 'production' )
        run: |
          echo run ${{ env.deploy_env }}-deploy-web
